main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("card/<slug:pk>", views.card, name="card"),
    path("collection/<int:pk>", views.collection, name="collection"),
    path(
        "collection/create",
        views.CreateCollectionView.as_view(),
        name="create-collection",
    ),
    path("adv-search", views.AdvSearchView.as_view(), name="adv-search"),
]

pokecardsV2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('main.urls', namespace="main")),
    path('', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('account', views.AccountView.as_view(), name="account"),
    path('profile', views.profile_view, name="profile"),
    path('sign-up', views.SignUpView.as_view(), name="sign-up"),
    path('sign-in', views.SignInView.as_view(), name="sign-in"),
    path('sign-out', views.sign_out, name="sign-out"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Set(models.Model):
    id = models.CharField(max_length=100, primary_key=True)  # string
    name = models.CharField(max_length=100, blank=True, null=True)  # string
    series = models.CharField(max_length=100, blank=True, null=True)  # string
    # int
    printed_total = models.IntegerField(null=True, blank=True)
    total = models.IntegerField(null=True, blank=True)  # int
    unlimited_legality = models.CharField(
        max_length=100, blank=True, null=True
    )  # string
    standard_legality = models.CharField(
        max_length=100, blank=True, null=True
    )  # string
    expanded_legality = models.CharField(
        max_length=100, blank=True, null=True
    )  # string
    ptcgo_code = models.CharField(max_length=100, blank=True, null=True)  # string
    release_date = models.DateField(blank=True, null=True)  # date
    updated_at = models.DateTimeField(blank=True, null=True)  # datetime
    symbol = models.URLField(blank=True, null=True)  # url
    logo = models.URLField(blank=True, null=True)  # url

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.name}"


class Card(models.Model):
    id = models.CharField(max_length=100, primary_key=True)  # string
    name = models.CharField(max_length=100, blank=True, null=True)  # string
    supertype = models.CharField(max_length=100, blank=True, null=True)  # string
    subtypes = models.CharField(max_length=100, blank=True, null=True)  # list(string)
    card_set = models.ForeignKey(
        "Set", on_delete=models.CASCADE, related_name="card_set"
    )  # hash
    number = models.CharField(max_length=100, blank=True, null=True)  # string
    artist = models.CharField(max_length=100, blank=True, null=True)  # string
    rarity = models.CharField(max_length=100, blank=True, null=True)  # string
    small_image = models.URLField(blank=True, null=True)  # url
    large_image = models.URLField(blank=True, null=True)  # url
    tcgplayer_prices_normal = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=8
    )  # hash
    tcgplayer_prices_holo = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=8
    )  # hash

    in_collection = models.BooleanField(default=False)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.name}"


class Collection(models.Model):
    title = models.CharField(max_length=256, null=True, blank=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    # card id is stored here like a favorites field
    cards = models.ManyToManyField(
        Card, related_name="inCollection", default=None, blank=True
    )

    created_by = models.ForeignKey(
        User, related_name="collection", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}"

main/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

INPUT_CLASSES = "rounded-lg"


class CollectionForm(forms.ModelForm):
    '''
    Basic model-form for users to create a collection
    '''
    title = forms.CharField(max_length=256, required=True, widget=forms.TextInput(
        attrs={'placeholder': '*Title...', 'class': INPUT_CLASSES}))
    description = forms.CharField(max_length=256, required=True, widget=forms.TextInput(
        attrs={'placeholder': '*Description...', 'class': INPUT_CLASSES}))

    class Meta:
        model = Collection
        fields = ('title', 'description')

main/views.py
from typing import Any
from django import http
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.views import View
from django.views.generic.edit import CreateView
from django.db.models.functions import Cast
from django.db.models import IntegerField
from pokemontcgsdk import Card as getCard, RestClient, Set as getSet
from my_secrets import secrets

from .forms import (
    CollectionForm,
)
from .models import *


API_KEY = secrets.API_KEY

RestClient.configure(API_KEY)


def index(request):
    context = {}
    return render(request, "main/index.html", context)


def card(request, pk):
    card = Card.objects.get(id=pk)
    card_data = getCard.find(pk)
    attacks = card_data.attacks
    if card_data.tcgplayer.prices.normal:
        price = card_data.tcgplayer.prices.normal.market
    elif card_data.tcgplayer.prices.holofoil:
        price = card_data.tcgplayer.prices.holofoil.market
    else:
        price = 0.00
    weaknesses = card_data.weaknesses
    resistances = card_data.resistances
    retreat_cost = card_data.retreatCost
    subtypes = card_data.subtypes
    hp = card_data.hp
    types = card_data.types
    abilities = card_data.abilities

    context = {
        "card": card,
        "attacks": attacks,
        "price": price,
        "weaknesses": weaknesses,
        "resistances": resistances,
        "retreat_cost": retreat_cost,
        "subtypes": subtypes,
        "types": types,
        "abilities": abilities,
        "hp": hp,
    }
    return render(request, "main/card.html", context)


@login_required
def collection(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    cards = collection.cards.all()
    context = {"collection": collection, "cards": cards}
    return render(request, "main/collection.html", context)


class CreateCollectionView(LoginRequiredMixin, CreateView):
    template_name = "main/create_collection.html"
    model = Collection
    fields = ["title", "description"]

    def get(self, request):
        form = CollectionForm()
        message = ""
        context = {"form": form, "message": message}
        return render(request, self.template_name, context)

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("main:collection", kwargs={"pk": self.object.id})


def is_valid_query(param):
    return param != "" and param is not None


class AdvSearchView(View):
    template_name = "main/adv_search.html"

    def get(self, request):
        message = ""
        context = {
            "message": message,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        name = request.POST.get("name")
        supertype = request.POST.get("supertype")
        subtypes = request.POST.get("subtypes")
        types = request.POST.get("types")
        hp = request.POST.get("hp")
        weaknesses = request.POST.get("weaknesses")
        resistances = request.POST.get("resistances")
        retreat_cost = request.POST.get("retreat_cost")
        set = request.POST.get("set")
        artist = request.POST.get("artist")
        rarity = request.POST.get("rarity")

        cards = getCard.where(q=f"name:{name}")

        #     supertype:{supertype} subtypes:{subtypes} types:{types} hp:{hp} weaknesses:{weaknesses} resistances:{resistances} retreatCost:{retreat_cost} set:{set} artist:{artist} rarity:{rarity}"
        # )

        message = ""
        context = {"message": message, "cards": cards}
        return render(request, "main/search_results.html", context)

main/templates/main/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
  <head>
    <meta name="description"
          content="Manage your pokemon card collection with our web app!" />
    <meta name="keywords" content="pokemon,cards,tcg,collection" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock title %}
    | Pokecards</title>
    {% tailwind_css %}
  </head>
  <body class="md:bg-gradient-to-r from-primary to-white bg-primary font-sans min-h-screen flex flex-col justify-between">
    <nav class="top-0 shadow-lg text-secondary text-lg font-semibold md:flex justify-between p-0.5 m-1 md:visible hidden">
      <div>
        <a href="{% url 'main:index' %}">Pokécards</a>
      </div>
      <div class="flex gap-3">
        {% if user.is_authenticated %}
          <div>
            <p>My Collections</p>
            <ul class="hidden">
              <li>
                <a href="#">Collection 1</a>
              </li>
            </ul>
          </div>
          <a href="{% url 'users:account' %}">Account</a>
          <a href="{% url 'users:sign-out' %}">Logout</a>
        {% else %}
          <a href="{% url 'users:sign-in' %}">Login</a>
          <a href="{% url 'users:sign-up' %}">Register</a>
        {% endif %}
      </div>
    </nav>
    <nav class="top-0 shadow-lg text-secondary text-lg font-semibold flex justify-between p-0.5 m-1 md:hidden visible">
      <div>
        <a href="#">mobile nav</a>
      </div>
    </nav>
    <div class="grow w-full">
      {% block content %}
      {% endblock content %}
      {% block script %}
        <script src="{% static 'main.js' %}"></script>
      {% endblock script %}
    </div>
    <footer class="bottom-0 shadow-inner md:visible invisible">
      <section class="flex justify-evenly p-0.5 m-1">
        <h2>
          Created by <span>Aaron Thompson</span>
        </h2>
        <p>
          Code found on <a class="text-secondary"
    href="https://github.com/Endeyr/pokecards"
    target="_blank"
    rel="noopener noreferrer">Github</a>
        </p>
      </section>
    </footer>
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
  </body>
</html>

main/templates/main/card.html
{% extends "main/base.html" %}
{% block title %}
  Card
{% endblock title %}
{% block content %}
  <section class="flex md:flex-row flex-col mt-4 p-2">
    <div class="flex md:hidden justify-center items-center ">
      <img height="max-h-fit"
           width="auto"
           class="m-1 p-0.25"
           src="{{ card.small_image }}"
           alt="{{ card.name }}" />
    </div>
    <div class="hidden md:inline md:basis-1/4 md:justify-center md:items-center">
      <img height="auto"
           width="auto"
           class="m-1 p-0.25"
           src="{{ card.large_image }}"
           alt="{{ card.name }}" />
    </div>
    <div class="md:basis-3/4 flex flex-col md:grid m-1 p-0.5">
      <div class="md:flex md:gap-2 md:justify-between m-1 p-0.5">
        <p class="m-1">
          <span class="font-bold">Name:</span> {{ card.name }}
        </p>
        <p class="m-1">
          <span class="font-bold">Subtype:</span>
          {% for type in subtypes %}{{ type }}{% endfor %}
        </p>
        <p class="m-1">
          <span class="font-bold">HP:</span> {{ hp }}
        </p>
        <p class="m-1">
          <span class="font-bold">Type:</span>
          {% for type in types %}{{ type }}{% endfor %}
        </p>
        <p class="m-1">
          <span class="font-bold">Price:</span> ${{ price }}
        </p>
      </div>
      <hr>
      <div class="md:flex md:gap-4 md:justify-start m-1 p-0.5">
        <div class="m-1">
          {% for ability in abilities %}
            <h3>
              <span class="font-bold">Ability:</span> {{ ability.name }}
            </h3>
            <p>{{ ability.text }}</p>
          {% endfor %}
        </div>
        <div class="flex flex-col m-1">
          {% for attack in attacks %}
            <h3>
              <span class="font-bold">Attack:</span> {{ attack.name }}
            </h3>
            <p class="flex flex-row w-auto">
              {% for cost in attack.cost %}<div>{{ cost }}</div>{% endfor %}
            </p>
            {% if attack.damage %}
              <p>
                <span class="font-bold">Damage:</span> {{ attack.damage }}
              </p>
            {% endif %}
            <p>{{ attack.text }}</p>
          {% endfor %}
        </div>
      </div>
      <hr>
      <div class="md:grid md:columns-4 md:gap-4 m-1 p-0.5">
        {% if card.rules != None %}
          <p class="m-1">
            <span class="font-bold">Rules:</span> {{ card.rules }}
          </p>
        {% endif %}
        <p class="m-1">
          <span class="font-bold">Weaknesses:</span>
          {% for weakness in weaknesses %}{{ weakness.type }}{% endfor %}
        </p>
        <p class="m-1">
          <span class="font-bold">Resistances:</span>
          {% for resistance in resistances %}{{ resistance.type }}{% endfor %}
        </p>
        <p class="m-1">
          <span class="font-bold">Retreat Cost:</span>
          {% for cost in retreat_cost %}<div>{{ cost }}</div>{% endfor %}
        </p>
        <p class="m-1">
          <span class="font-bold">Artist:</span> {{ card.artist }}
        </p>
        <p class="m-1">
          <span class="font-bold">Rarity:</span> {{ card.rarity }}
        </p>
        <p class="m-1">
          <span class="font-bold">Set:</span> {{ card.card_set }}
        </p>
        <p class="m-1">
          <span class="font-bold">Number:</span> {{ card.number }}
        </p>
        <div class="col-start-2 m-1">
          {% if card.in_collection %}
            <button class="text-white p-2 m-1 rounded-full bg-danger">Remove from Collection</button>
          {% else %}
            <button class="text-white p-2 m-1 rounded-full bg-secondary">Add to Collection</button>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

main/templates/main/collection.html
{% extends "main/base.html" %}
{% block title %}
  {{ collection.title }}
{% endblock title %}
{% block content %}
  <section class="flex flex-col items-center justify-center gap-3 m-1 p-0.5">
    <p class="text-lg">{{ collection.title }}</p>
    <div class="flex items-center gap-3 m-1 p-0.5">
      <div>
        <button id="dropdownViewButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full">
          View
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">List</li>
            <li class="block p-2">Image</li>
          </ul>
        </div>
      </div>
      <div>
        <button id="dropdownSortButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full justify-center">
          Sort
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">Name</li>
            <li class="block p-2">Release Date</li>
            <li class="block p-2">Set</li>
            <li class="block p-2">Number</li>
            <li class="block p-2">Rarity</li>
          </ul>
        </div>
      </div>
      <div>
        <button id="dropdownOrderButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full ">
          Order
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2 w-full">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">Asc</li>
            <li class="block p-2">Dsc</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="visible relative overflow-auto">
      <table class="w-full text-base text-left border border-collapse ">
        <thead class="text-lg uppercase bg-gray-200">
          <tr>
            <th scope="col" class="p-3">Set</th>
            <th scope="col" class="p-3">No</th>
            <th scope="col" class="p-3">Name</th>
            <th scope="col" class="p-3">Rarity</th>
            <th scope="col" class="p-3">Types</th>
            <th scope="col" class="p-3">Supertype</th>
            <th scope="col" class="p-3">Subtypes</th>
            <th scope="col" class="p-3">Price</th>
            <th scope="col" class="p-3">Collection</th>
          </tr>
        </thead>
        <tbody class="bg-white ">
          {% for card in cards %}
            <tr>
              <td class="p-3 border-b border-secondary">{{ card.card_set }}</td>
              <td class="p-3 border-b border-secondary">{{ card.number }}</td>
              <td class="p-3 border-b border-secondary">{{ card.name }}</td>
              <td class="p-3 border-b border-secondary">{{ card.rarity }}</td>
              <td class="p-3 border-b border-secondary">{{ card.types }}</td>
              <td class="p-3 border-b border-secondary">{{ card.supertype }}</td>
              <td class="p-3 border-b border-secondary">{{ card.subtypes }}</td>
              <td class="p-3 border-b border-secondary">{{ card.tcgplayer_prices }}</td>
              <td class="p-3 border-b border-secondary">
                <button type="button"
                        class="bg-danger rounded-lg p-2 text-white font-bold text-center">Remove</button>
                <button type="button"
                        class="bg-secondary rounded-lg p-2 text-white font-bold text-center hidden">Add</button>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="grid grid-cols-5 gap-3">
      {% for card in cards %}
        <div>
          <a href="{% url 'main:card' pk=card.id %}">
            <img height="auto"
                 width="auto"
                 src="{{ card.large_image }}"
                 alt="{{ card.name }}" />
          </a>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock content %}

main/templates/main/create_collection.html
{% extends "main/base.html" %}
{% block title %}
  Create Collection
{% endblock title %}
{% block content %}
  <section class="h-[80vh] flex flex-col justify-center items-center gap-3">
    {% if message %}<p class="bg-danger w-1/4 text-center font-extrabold">{{ message }}</p>{% endif %}
    {% if form.errors %}<p class="bg-danger w-1/4 text-center font-extrabold">{{ form.errors }}</p>{% endif %}
    <form action="{% url 'main:create-collection' %}"
          method="post"
          class="flex flex-col justify-center items-end gap-1">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button type="submit" class=" text-white p-2 m-1 rounded-full bg-secondary">Submit</button>
      </div>
    </form>
  </section>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
  Home
{% endblock title %}
{% block content %}
  <section>
    <article class="h-[80vh] flex flex-col justify-center items-center gap-3">
      <img width="auto"
           height="auto"
           src="{% static 'images/pikachu.png' %}"
           alt="pikachu"
           class="m-1 p-0.25 h-64" />
      <div class="flex flex-col justify-center items-center gap-2">
        <h1 class="text-2xl">Welcome to Pokécards!</h1>
        <p class="text-2xl">A webapp to manage your PokémonTCG collection.</p>
      </div>
    </article>
    <article class="h-screen flex justify-evenly items-center gap-3">
      <div>
        <img width="auto"
             height="auto"
             src="{% static 'images/pokeball.png' %}"
             alt="pokeball"
             class="m-1 p-0.25 h-64" />
      </div>
      <div class="flex flex-col justify-center items-center gap-2">
        <h2>Start your collection!</h2>
        <a href="{% url 'main:create-collection' %}"
           class="text-white p-2 m-1 rounded-full bg-secondary">Create Collection</a>
      </div>
    </article>
    <article class="h-screen flex justify-evenly items-center gap-3">
      <div class="flex flex-col justify-center items-center gap-2">
        <form class="flex flex-col justify-center items-center gap-2">
          <label for="card-search">Search for your favorite card!</label>
          <div>
            <input type="search"
                   id="card-search"
                   class="rounded-lg"
                   placeholder="Search Cards, Sets..."
                   required />
            <button class=" text-white p-2 m-1 rounded-full bg-secondary" type="submit">Search</button>
          </div>
        </form>
        <div>
          <a href="{% url 'main:adv-search' %}"
             class=" text-white p-2 m-1 rounded-full bg-secondary">Advanced Search</a>
        </div>
      </div>
      <div>
        <img width="auto"
             height="auto"
             src="{% static 'images/legendary.png' -%}"
             alt="legendaries"
             class="m-1 p-0.25 h-64" />
      </div>
    </article>
  </section>
{% endblock content %}

main/templates/main/search_results.html
{% extends "main/base.html" %}
{% block title %}
  Search Results
{% endblock title %}
{% block content %}
  <section class="flex flex-col items-center justify-center gap-3 m-1 p-0.5">
    <p class="text-lg">Search Results</p>
    <p>{{ message }}</p>
    <div class="flex items-center gap-3 m-1 p-0.5">
      <div>
        <button id="dropdownViewButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full">
          View
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">List</li>
            <li class="block p-2">Image</li>
          </ul>
        </div>
      </div>
      <div>
        <button id="dropdownSortButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full justify-center">
          Sort
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">Name</li>
            <li class="block p-2">Release Date</li>
            <li class="block p-2">Set</li>
            <li class="block p-2">Number</li>
            <li class="block p-2">Rarity</li>
          </ul>
        </div>
      </div>
      <div>
        <button id="dropdownOrderButton"
                type="button"
                data-dropdown-toggle="dropdown"
                class="font-bold bg-secondary text-white hover:bg-gray-600 rounded-lg p-2 text-center inline-flex items-center w-full ">
          Order
          <svg class="w-2.5 h-2.5 ml-2.5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>
        <div class="hidden z-10 bg-secondary text-white divide-y divide-primary rounded-lg shadow p-2 w-full">
          <ul aria-labelledby="dropdownViewButton" class="text-sm">
            <li class="block p-2">Asc</li>
            <li class="block p-2">Dsc</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="hidden relative overflow-auto">
      <table class="w-full text-base text-left border border-collapse ">
        <thead class="text-lg uppercase bg-gray-200">
          <tr>
            <th scope="col" class="p-3">Set</th>
            <th scope="col" class="p-3">No</th>
            <th scope="col" class="p-3">Name</th>
            <th scope="col" class="p-3">Rarity</th>
            <th scope="col" class="p-3">Types</th>
            <th scope="col" class="p-3">Supertype</th>
            <th scope="col" class="p-3">Subtypes</th>
            <th scope="col" class="p-3">Price</th>
            <th scope="col" class="p-3">Collection</th>
          </tr>
        </thead>
        <tbody class="bg-white ">
          {% for card in cards %}
            <tr>
              <td class="p-3 border-b border-secondary">{{ card.set.name }}</td>
              <td class="p-3 border-b border-secondary">{{ card.number }}</td>
              <td class="p-3 border-b border-secondary">{{ card.name }}</td>
              <td class="p-3 border-b border-secondary">{{ card.rarity }}</td>
              <td class="p-3 border-b border-secondary">
                {% for type in card.types %}{{ type }}{% endfor %}
              </td>
              <td class="p-3 border-b border-secondary">{{ card.supertype }}</td>
              <td class="p-3 border-b border-secondary">
                {% for type in card.subtypes %}{{ type }}{% endfor %}
              </td>
              <td class="p-3 border-b border-secondary">
                {% if card.tcgplayer.prices.normal %}
                  ${{ card.tcgplayer.prices.normal.market }}
                {% elif card.tcgplayer.prices.holofoil %}
                  ${{ card.tcgplayer.prices.holofoil.market }}
                {% else %}
                  NA
                {% endif %}
              </td>
              <td class="p-3 border-b border-secondary">
                <button type="button"
                        id="remove"
                        class="bg-danger rounded-lg p-2 text-white font-bold text-center hidden">Remove</button>
                <button type="button"
                        id="add"
                        class="bg-secondary rounded-lg p-2 text-white font-bold text-center">Add</button>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="grid grid-cols-5 gap-3">
      {% for card in cards %}
        <div>
          <a href="{% url 'main:card' pk=card.id %}">
            <img height="auto"
                 width="auto"
                 src="{{ card.images.large }}"
                 alt="{{ card.name }}" />
          </a>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock content %}